# Документация для админки
openapi: 3.0.3

info:
  title: Документация
  version: 1.0.0

servers:
  - url: "/api"

paths:
  '/categories':
    get:
      tags:
        - Категории
      summary: Получить список категорий
      responses:
        200:
          description: 'ok'


